# Generated by Django 3.2.8 on 2023-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'verbose_name_plural': 'Attendance Management System'},
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
    ]
