# Generated by Django 3.2.8 on 2023-05-28 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20230526_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='isabsenteeism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='overtime',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
