# Generated by Django 3.2.8 on 2023-05-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20230528_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'verbose_name_plural': 'OverTime'},
        ),
    ]
