# Generated by Django 3.2.8 on 2023-05-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_overtime_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='start_date',
        ),
        migrations.AddField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 23, 44, 12, 632438)),
        ),
        migrations.AddField(
            model_name='overtime',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
