# Generated by Django 3.2.8 on 2023-05-28 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20230528_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 0, 9, 32, 955148)),
        ),
    ]
