# Generated by Django 3.2.8 on 2023-05-29 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_overtime_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 19, 46, 6, 865430)),
        ),
    ]
