# Generated by Django 3.2.8 on 2023-05-29 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20230529_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_title',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 10, 47, 573330)),
        ),
    ]
