# Generated by Django 3.2.8 on 2023-05-29 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20230529_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 11, 54, 336445)),
        ),
    ]
