# Generated by Django 3.2.8 on 2023-05-30 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_overtime_end_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='AttendanceRecord',
        ),
        migrations.AlterField(
            model_name='overtime',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 20, 56, 4, 715399)),
        ),
    ]
